### ISSUE TITLE
`collapse::t_list()` applied twice does not return the original list (because it adds `V1, ...` names)

### ISSUE THREAD

**Issue by orgadish** [SebKrantz/collapse#488] opened 2023-11-06 18:56 UTC
Not sure if this is a bug or by design:

`collapse::t_list()` adds `V1, ...` names to a list. This means that applying it twice does not return the original list.

I thought initially this is because it is designed to work the same on data.frames as lists, but it does not work on data.frames either.

``` r
# List without names -- names are added at both levels
list(1:5, 1:5) |> 
  collapse::t_list() |> 
  collapse::t_list()
#> $V1
#> V1 V2 V3 V4 V5 
#>  1  2  3  4  5 
#> 
#> $V2
#> V1 V2 V3 V4 V5 
#>  1  2  3  4  5

# List with names -- names are added within each element
list(a = 1:5, b = 1:5) |> 
  collapse::t_list() |> 
  collapse::t_list()
#> $a
#> V1 V2 V3 V4 V5 
#>  1  2  3  4  5 
#> 
#> $b
#> V1 V2 V3 V4 V5 
#>  1  2  3  4  5

# Data frame -- does not work at all
data.frame(a = 1:5, b = 1:5) |> 
  collapse::t_list() |> 
  collapse::t_list()
#> [1] a b
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2023-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       macOS Ventura 13.5.2
#>  system   x86_64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2023-11-06
#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  collapse      2.0.3   2023-10-17 [1] CRAN (R 4.3.0)
#>  Rcpp          1.0.11  2023-07-06 [1] CRAN (R 4.3.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by SebKrantz** [comment] 2023-11-06 19:49
Thanks. This is because `t_list()` wraps `mctl(do.call(rbind, l), names = TRUE)`. `mctl()` is for converting matrix columns to list, and, if names = TRUE and there are not names, creates them. But I agree it is not sensible inside `t_list()`. I will adjust the code as I find time.

**Comment by SebKrantz** [comment] 2023-11-06 19:59
Actually I just fixed it, very easy. You can `remotes::install_github("SebKrantz/collapse", ref = "development")` to check it out.

**Comment by orgadish** [comment] 2023-11-07 01:21
It looks good in my quick testing!

**Comment by orgadish** [comment] 2023-11-07 04:13
@SebKrantz It looks like your new implementation does not quite work with multiple layers of names:
``` r
l <- list(A=list(a=1:10), B=list(b=1:10))
names(l)
#> [1] "A" "B"
lapply(l, names)
#> $A
#> [1] "a"
#> 
#> $B
#> [1] "b"

l2 <- l |> 
  collapse::t_list() |> 
  collapse::t_list()
names(l2)
#> [1] "A" "B"
lapply(l2, names)
#> $A
#> [1] "a"
#> 
#> $B
#> [1] "a"
```

<sup>Created on 2023-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       macOS Ventura 13.5.2
#>  system   x86_64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2023-11-06
#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  collapse      2.0.5   2023-11-07 [1] Github (SebKrantz/collapse@4b0119e)
#>  Rcpp          1.0.11  2023-07-06 [1] CRAN (R 4.3.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by orgadish** [comment] 2023-11-07 04:16
Thinking on it some more, this might actually be the expected behavior, since the intermediate transposed list cannot keep both names (I think?).

**Comment by SebKrantz** [comment] 2023-11-07 20:34
Hi, yes, this is the expected behavior. The `do.call(rbind, l)` step gets rid of `b`, If you have a symmatric nested list it works well

``` r
library(collapse)
#> collapse 2.0.5, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
l <- list(a = list(c = 1, d = 2), b = list(c = 3, d = 4))
str(l)
#> List of 2
#>  $ a:List of 2
#>   ..$ c: num 1
#>   ..$ d: num 2
#>  $ b:List of 2
#>   ..$ c: num 3
#>   ..$ d: num 4
str(t_list(l))
#> List of 2
#>  $ c:List of 2
#>   ..$ a: num 1
#>   ..$ b: num 3
#>  $ d:List of 2
#>   ..$ a: num 2
#>   ..$ b: num 4
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment] 2023-11-07 20:35
I'll close the issue now, the fix will be available quite soon.

**Closed by SebKrantz** 2023-11-07 20:35 UTC
