### ISSUE TITLE
num_vars and integer 64

### ISSUE THREAD

**Issue by docfleetwood** [SebKrantz/collapse#536] opened 2024-02-17 17:47 UTC
Is num-vars() designed to identify integer64 variables as numeric? Because I have a dataset where it is not identifying integer64 as numeric, but I'm not sure if that is a bug or by design and I can't seem to find the answer on your site.

**Comment by SebKrantz** [comment] 2024-02-17 20:02
Thanks, yeah there is currently no exception for that, but I added it now. The issue is that integer64, has a class "integer64", and is thus recognized as an object (like Date, POSIXct etc.) instead of a plain numeric vectors. See [here](https://sebkrantz.github.io/collapse/articles/collapse_object_handling.html#selecting-columns-by-data-type) for more information.

**Comment by SebKrantz** [comment] 2024-02-17 20:08
Just pushed the fix to master, you can get it from there or R-universe in like 1h. As described in the vignette, num_vars() is very fast, but has the constraint that it does not check R-level methods for `is.numeric`, and thus excludes objects from being recognized as numeric, except for definied exceptions, which now include "ts", "units" and "integer64".

**Closed by SebKrantz** 2024-02-17 20:08 UTC
